global: 
  scrape_interval: 10s
scrape_configs: 
  - job_name: prometheus-werter
    static_configs: 
      - targets: 
        - localhost:9090
  - job_name: aspnet-metrics
    static_configs: 
      - targets: 
        - web-api:80
  - job_name: docker-metrics
    static_configs: 
      - targets: 
        - docker-export:9417     